services:
    mongo:
        image: mongo
        container_name: block52-payments
        restart: always
        environment:
            MONGO_INITDB_DATABASE: payments
            # No auth for now
            # MONGO_INITDB_ROOT_USERNAME: root
            # MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27018:27017
        volumes:
            - mongo-data:/data/db

    # Node.js Express application
    api:
        build:
            context: ./js
            dockerfile: Dockerfile
        container_name: block52-api
        restart: unless-stopped
        environment:
            - NODE_ENV=production
            - NODE_URL=https://node1.block52.xyz
            - PORT=8080
            - MONGO_URI=mongodb://mongo:27017/payments
        ports:
            - "8080:8080"
        depends_on:
            - mongo
        volumes:
            - ./js:/usr/src/app
            - /usr/src/app/node_modules

volumes:
    mongo-data:
# networks:
#   block52-network:
#     driver: bridge
