name: PVM UnitTests

on: [push]

defaults:
  run:
    working-directory: ./pvm/ts

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18'
      - name: Install dependencies
        run: yarn install
      - run: yarn test
