name: UnitTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18'
      - name: Install dependencies
        run: cd ~/pvm/ts && yarn install
      - run: cd ~/pvm/ts && yarn test
